fn main() {
    // panic!("出错了 不可恢复");

    let a=["a","2"];
    println!("{}",a[2]);
}
